//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace James_Thew.context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Anouncement
    {
        [Required]
        public int Id { get; set; }
        [Required]

        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public System.DateTime Date_Posted { get; set; }
    }
}
