//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace James_Thew.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string Contents { get; set; }
        public string Rating { get; set; }
        public string User_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
