//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace James_Thew.context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class James_ThewEntities1 : DbContext
    {
        public James_ThewEntities1()
            : base("name=James_ThewEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<Racipies_james> Racipies_james { get; set; }
        public virtual DbSet<Anouncement> Anouncement { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<FAQs> FAQs { get; set; }
        public virtual DbSet<User_recepie> User_recepie { get; set; }
        public virtual DbSet<winnerstable> winnerstable { get; set; }
        public virtual DbSet<Tips> Tips { get; set; }
        public virtual DbSet<Profile_Image> Profile_Image { get; set; }
    }
}
