//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace James_Thew.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racipies_james
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Ingredient { get; set; }
        public string CookingProcedure { get; set; }
        public bool IsFree { get; set; }
        public string Image { get; set; }
    }
}
