//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace James_Thew.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_recepie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_recepie()
        {
            this.winnerstable = new HashSet<winnerstable>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Ingrdient { get; set; }
        public string CookingProcedure { get; set; }
        public string User_Id { get; set; }
        public bool IsActive { get; set; }
        public string Post { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<winnerstable> winnerstable { get; set; }
    }
}
